name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Executer le script Python avec le secret
        env:
          # On récupère le secret GitHub pour le stocker dans une variable d'environnement locale MY_SECRET
          MY_SECRET: ${{ secrets.SECRET_API_TOKEN }}
        run: python job.py
